c       PROGRAM MAIN
c       IMPLICIT DOUBLE PRECISION (A-H,O-Z)
ccc       INTEGER ND,CHANNEL
c       INTEGER ND
cc       COMMON/CHANNEL/CHANNEL
c       EXTERNAL BORNGRADDinc,BORNDY
c
c!!! Common block
c      INTEGER MODL,MODE,MODP,CHANNEL,NF,ORD
c      DOUBLE PRECISION RS,CA,CF,TF,XNC,XMT,XMB,XMC,Q,XMUR,XMUF,AS
c      DOUBLE PRECISION XLFR,XLQF,XLQR
c      DOUBLE PRECISION XLAMBDA,XKAP
c      CHARACTER*50 PREFIX
c
c      COMMON/ADDRS/MODL
c      COMMON/ISET/MODE,MODP
c      COMMON/MACHINE/RS
c      COMMON/CHANNEL/CHANNEL
c      COMMON/COLORS/CA,CF,TF,XNC
c      COMMON/FLAVOUR/NF
c      COMMON/PDFGROUP/PREFIX
c      COMMON/XMASS/XMT,XMB,XMC
c      COMMON/NORDER/ORD
c      COMMON/XXMH/Q,XMUR,XMUF
c      COMMON/ALS/AS
c      COMMON/COUPLING/XLAMBDA,XKAP
c      COMMON/SCALES/XLFR,XLQF,XLQR
c
c       Q=300D0
c       QQ=300D0
c       XMS=4000D0
c       ND=3
c       CHANNEL=2
cc       CALL FACTGR(Q,XMS,ND,FGR)
c       WRITE(*,*)"FGR=",FGR
cc       RESULT1=BORNGRADDinc(QQ,XMS,nd)
c       RESULT2=BORNDY(Q)
cc       WRITE(*,*)"BORN ADD=",RESULT1
c       WRITE(*,*)"BORN DY=",RESULT2
c       END PROGRAM MAIN
c
      DOUBLE PRECISION FUNCTION BORNGRRSinc(Q,Lambda) 
      IMPLICIT NONE
      DOUBLE COMPLEX II,ONE,FUNX,Q,Lambda,BORNggGRinc,bornRS
      DOUBLE PRECISION FX,MH,MT,ALPHAS,AS
c      include 'constant.h'

!!!    BORN STARTS 
       bornRS=2D0*Q**2/Lambda**2
       BORNggGRinc=bornRS
!!!    BORN ENDS 
      RETURN
      END


      DOUBLE PRECISION FUNCTION BORNDY(XMH)
      IMPLICIT NONE
      DOUBLE PRECISION XMH,XDEL
      DOUBLE PRECISION CQQB0_DY,FNORM
      INTEGER MODL,MODE,MODP,CHANNEL,NF,ORD
      DOUBLE PRECISION RS,CA,CF,TF,XNC,XMT,XMB,XMC,Q,XMUR,XMUF,AS
      DOUBLE PRECISION XLFR,XLQF,XLQR
      DOUBLE PRECISION XLAMBDA,XKAP
      CHARACTER*50 PREFIX
      COMMON/MACHINE/RS
      include 'constants.h'

       XNC=3.0D0
       XDEL=1.0D0
c       RS=13000.0D0
      CQQB0_DY=2.0D0*PI/XNC*XDEL
C      FNORM=2.0D0*XMH/2.0D0/RS/RS*389.3856741D+9  ! d\Sigma/dQ in fb
      FNORM=XMH**2.0d0/2.0D0/RS/RS*389.3856741D+6 ! Q^2*d\Sigma/dQ^2 in pb

      BORNDY = FNORM*CQQB0_DY 
      RETURN
      END

      DOUBLE PRECISION FUNCTION BORNGRinc(XMH)
      IMPLICIT NONE 
c      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION XMH,XMS,FGR
      INTEGER ND
      DOUBLE PRECISION XDEL,FNORM,CQQB0_GR,CGG0_GR
      DOUBLE PRECISION BORNggGRinc,BORNqqbGRinc

!!! Common block
      INTEGER MODL,MODE,MODP,CHANNEL,NF,ORD
      DOUBLE PRECISION RS,CA,CF,TF,XNC,XMT,XMB,XMC,Q,XMUR,XMUF,AS
      DOUBLE PRECISION XLFR,XLQF,XLQR
      DOUBLE PRECISION XLAMBDA,XKAP
      CHARACTER*50 PREFIX

      COMMON/ADDRS/MODL
      COMMON/ISET/MODE,MODP
      COMMON/MACHINE/RS
      COMMON/CHANNEL/CHANNEL
      COMMON/COLORS/CA,CF,TF,XNC
      COMMON/FLAVOUR/NF
      COMMON/PDFGROUP/PREFIX
      COMMON/XMASS/XMT,XMB,XMC
      COMMON/NORDER/ORD
      COMMON/XXMH/Q,XMUR,XMUF
      COMMON/ALS/AS
      COMMON/COUPLING/XLAMBDA,XKAP
      COMMON/SCALES/XLFR,XLQF,XLQR


       REAL*8 c00,ams,amh,aam1,c0,aamh
c       common/xpar/c00,ams,amh
       COMMON/rs_par/aam1,c0,aamh
      include 'constants.h'

      XDEL=1.0D0
      CQQB0_GR = PI/8.0D0/XNC*XDEL
      CGG0_GR  = PI/2.0D0/(XNC*XNC-1.0D0)*XDEL
      FNORM=2.0D0*XMH/2.0D0/RS/RS*389.3856741D+9

       IF (CHANNEL .EQ. 1) THEN !! qqb
       BORNGRinc=FNORM*CQQB0_GR
       ELSEIF (CHANNEL .EQ. 2) THEN !! gg 
       BORNGRinc=FNORM*CGG0_GR
       ENDIF
      RETURN
      END
c      include 'bornaddon.h'
