---
kinematics :
  incoming_momenta: [ p1,p2 ]
  outgoing_momenta: [ p3 ]
  momentum_conservation: [p3, "p1 + p2 "]
  kinematic_invariants:
    - [s, 2]
  scalarproduct_rules:
    - [[p1,p1],  0]
    - [[p2,p2],  0]
    - [[p1+p2,p1+p2],  s]
