      DATA Denol(1  ,1)/         1/                                    
      DATA (CL(i,1  ,1),i=1  ,1  ) / -4/                               
C               T[ 2,1]                                                   
C  
      DATA Denol(1  ,2)/         1/                                    
      DATA (CL(i,1  ,2),i=1  ,1  ) / -4/                               
C               T[ 2,1]                                                   
C  
