#############################################
#############################################
integralfamilies:
  - name: "F1"
    loop_momenta: [k1]
    propagators:
      - [ "k1", 0 ]
      - [ "k1-p1", 0 ]
      - [ "k1-p1-p2", 0 ]
