      SUBROUTINE cmatrix1(P1,k,ANS)
C  
C Generated by MadGraph II                                              
C MadGraph StandAlone Version
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P(0:3,NEXTERNAL)
C  
C FOR PROCESS : u u~ -> e- e+  
C  
C Crossing   1 is u u~ -> e- e+  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      include "nexternal2.inc"
      INTEGER                 NCOMB,     NCROSS         
      PARAMETER (             NCOMB=  16, NCROSS=  1)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*NCROSS)
C  
C ARGUMENTS 
C  
      REAL*8 P1(0:3,NEXTERNAL2),ANS(NCROSS)
C  
C LOCAL VARIABLES 
C  
      INTEGER NHEL(NEXTERNAL2,NCOMB),NTRY
      integer k
      REAL*8 T, P(0:3,NEXTERNAL2)
      REAL*8 mat1
      INTEGER IHEL,IDEN(NCROSS),IC(NEXTERNAL2,NCROSS)
      INTEGER IPROC,JC(NEXTERNAL2), I
      LOGICAL GOODHEL(NCOMB,NCROSS)
      DATA NTRY/0/
      DATA GOODHEL/THEL*.FALSE./
      DATA (NHEL(IHEL,   1),IHEL=1, 4) /-1,-1,-1,-1/
      DATA (NHEL(IHEL,   2),IHEL=1, 4) /-1,-1,-1, 1/
      DATA (NHEL(IHEL,   3),IHEL=1, 4) /-1,-1, 1,-1/
      DATA (NHEL(IHEL,   4),IHEL=1, 4) /-1,-1, 1, 1/
      DATA (NHEL(IHEL,   5),IHEL=1, 4) /-1, 1,-1,-1/
      DATA (NHEL(IHEL,   6),IHEL=1, 4) /-1, 1,-1, 1/
      DATA (NHEL(IHEL,   7),IHEL=1, 4) /-1, 1, 1,-1/
      DATA (NHEL(IHEL,   8),IHEL=1, 4) /-1, 1, 1, 1/
      DATA (NHEL(IHEL,   9),IHEL=1, 4) / 1,-1,-1,-1/
      DATA (NHEL(IHEL,  10),IHEL=1, 4) / 1,-1,-1, 1/
      DATA (NHEL(IHEL,  11),IHEL=1, 4) / 1,-1, 1,-1/
      DATA (NHEL(IHEL,  12),IHEL=1, 4) / 1,-1, 1, 1/
      DATA (NHEL(IHEL,  13),IHEL=1, 4) / 1, 1,-1,-1/
      DATA (NHEL(IHEL,  14),IHEL=1, 4) / 1, 1,-1, 1/
      DATA (NHEL(IHEL,  15),IHEL=1, 4) / 1, 1, 1,-1/
      DATA (NHEL(IHEL,  16),IHEL=1, 4) / 1, 1, 1, 1/
      DATA (  IC(IHEL,  1),IHEL=1, 4) / 1, 2, 3, 4/
      DATA (IDEN(IHEL),IHEL=  1,  1) /  36/
C ----------
C BEGIN CODE
C ----------
      NTRY=NTRY+1
      DO IPROC=1,NCROSS
      CALL SWITCHMOM(P1,P,IC(1,IPROC),JC,NEXTERNAL2)
      DO IHEL=1,NEXTERNAL2
         JC(IHEL) = +1
      ENDDO
      ANS(IPROC) = 0D0
          DO IHEL=1,NCOMB
             IF (GOODHEL(IHEL,IPROC) .OR. NTRY .LT. 2) THEN
                 T=mat1(P ,NHEL(1,IHEL),JC(1),k)            
               ANS(IPROC)=ANS(IPROC)+T
               IF (T .ne. 0D0 .AND. .NOT.    GOODHEL(IHEL,IPROC)) THEN
                   GOODHEL(IHEL,IPROC)=.TRUE.
               ENDIF
             ENDIF
          ENDDO
      ANS(IPROC)=ANS(IPROC)/DBLE(IDEN(IPROC))
      ENDDO
c      print*,"ANS: ",ANS
      END
       
       
      REAL*8 FUNCTION mat1(P,NHEL,IC,k)
C  
C Generated by MadGraph II                                              
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL)
C  
C FOR PROCESS : u u~ -> e- e+  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NGRAPHS,    NEIGEN 
      PARAMETER (NGRAPHS=   1,NEIGEN=  1) 
      include "nexternal2.inc"
      include "emitspecinfo.inc"
      INTEGER    NWAVEFUNCS     , NCOLOR
      PARAMETER (NWAVEFUNCS=   5, NCOLOR=   1) 
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C  
C ARGUMENTS 
C  
      REAL*8 P(0:3,NEXTERNAL2)
      INTEGER NHEL(NEXTERNAL2), IC(NEXTERNAL2)
C  
C LOCAL VARIABLES 
C  
      INTEGER I,J
      integer k
      COMPLEX*16 ZTEMP
      REAL*8 DENOL(NCOLOR,tdn), CL(NCOLOR,NCOLOR,tdn)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(18,NWAVEFUNCS)
C  
C GLOBAL VARIABLES
C  
      include "coupl.inc"
C  
C COLOR DATA
C  
      include "allcolormat1.inc"
C ----------
C BEGIN CODE
C ----------
      CALL IXXXXX(P(0,1   ),ZERO ,NHEL(1   ),+1*IC(1   ),W(1,1   ))        
      CALL OXXXXX(P(0,2   ),ZERO ,NHEL(2   ),-1*IC(2   ),W(1,2   ))        
      CALL OXXXXX(P(0,3   ),ZERO ,NHEL(3   ),+1*IC(3   ),W(1,3   ))        
      CALL IXXXXX(P(0,4   ),ZERO ,NHEL(4   ),-1*IC(4   ),W(1,4   ))        
      CALL JIOXXX(W(1,1   ),W(1,2   ),GAU ,ZERO    ,AWIDTH  ,W(1,5   ))    
      CALL IOVXXX(W(1,4   ),W(1,3   ),W(1,5   ),GAL ,AMP(1   ))            
      JAMP(   1) = -AMP(   1)
      mat1 = 0.D0 
      DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NCOLOR
              ZTEMP = ZTEMP + CL(J,I,k)*JAMP(J)
          ENDDO
          mat1 =mat1+ZTEMP*DCONJG(JAMP(I))/DENOL(I,k) 
      ENDDO
c      CALL GAUGECHECK(JAMP,ZTEMP,EIGEN_VEC,EIGEN_VAL,NCOLOR,NEIGEN) 
      END
       
       
      SUBROUTINE cmatrix1dh(P1,k,ANS,x,y)
C  
C Generated by MadGraph II                                              
C MadGraph StandAlone Version
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P(0:3,NEXTERNAL)
C  
C FOR PROCESS : u u~ -> e- e+  
C  
C Crossing   1 is u u~ -> e- e+  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      include "nexternal2.inc"
      include "emitspecinfo.inc"
      INTEGER                 NCOMB,     NCROSS         
      PARAMETER (             NCOMB=  16, NCROSS=  1)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*NCROSS)
C  
C ARGUMENTS 
C  
      REAL*8 P1(0:3,NEXTERNAL2)
      COMPLEX*16 ANS(NCROSS)
C  
C LOCAL VARIABLES 
C  
      INTEGER NHEL(NEXTERNAL2,NCOMB),NTRY
      integer k
      REAL*8 P(0:3,NEXTERNAL2)
      COMPLEX*16 T
      COMPLEX*16 mat1dh
      INTEGER IHEL,IDEN(NCROSS),IC(NEXTERNAL2,NCROSS)
      INTEGER IPROC,JC(NEXTERNAL2), I
      LOGICAL GOODHEL(NCOMB,NCROSS)
C kouhei mod
      integer x,y,z
C kouhei mod
      DATA NTRY/0/
      DATA GOODHEL/THEL*.FALSE./
      DATA (NHEL(IHEL,   1),IHEL=1, 4) /-1,-1,-1,-1/
      DATA (NHEL(IHEL,   2),IHEL=1, 4) /-1,-1,-1, 1/
      DATA (NHEL(IHEL,   3),IHEL=1, 4) /-1,-1, 1,-1/
      DATA (NHEL(IHEL,   4),IHEL=1, 4) /-1,-1, 1, 1/
      DATA (NHEL(IHEL,   5),IHEL=1, 4) /-1, 1,-1,-1/
      DATA (NHEL(IHEL,   6),IHEL=1, 4) /-1, 1,-1, 1/
      DATA (NHEL(IHEL,   7),IHEL=1, 4) /-1, 1, 1,-1/
      DATA (NHEL(IHEL,   8),IHEL=1, 4) /-1, 1, 1, 1/
      DATA (NHEL(IHEL,   9),IHEL=1, 4) / 1,-1,-1,-1/
      DATA (NHEL(IHEL,  10),IHEL=1, 4) / 1,-1,-1, 1/
      DATA (NHEL(IHEL,  11),IHEL=1, 4) / 1,-1, 1,-1/
      DATA (NHEL(IHEL,  12),IHEL=1, 4) / 1,-1, 1, 1/
      DATA (NHEL(IHEL,  13),IHEL=1, 4) / 1, 1,-1,-1/
      DATA (NHEL(IHEL,  14),IHEL=1, 4) / 1, 1,-1, 1/
      DATA (NHEL(IHEL,  15),IHEL=1, 4) / 1, 1, 1,-1/
      DATA (NHEL(IHEL,  16),IHEL=1, 4) / 1, 1, 1, 1/
      DATA (  IC(IHEL,  1),IHEL=1, 4) / 1, 2, 3, 4/
      DATA (IDEN(IHEL),IHEL=  1,  1) /  36/
C ----------
C BEGIN CODE
C ----------
      NTRY=NTRY+1
      DO IPROC=1,NCROSS
      CALL SWITCHMOM(P1,P,IC(1,IPROC),JC,NEXTERNAL2)
      DO IHEL=1,NEXTERNAL2
         JC(IHEL) = +1
      ENDDO
      ANS(IPROC) = 0D0
C kouhei mod
       z = x*y
C kouhei mod
          DO IHEL=1,NCOMB
C kouhei mod
          if (nhel(emi(k),ihel) .eq. x) then
C kouhei mod
                 T=mat1dh(P,k,NHEL(1,IHEL),JC(1),z)            
               ANS(IPROC)=ANS(IPROC)+T
C kouhei mod
            endif
C kouhei mod
          ENDDO
      ANS(IPROC)=ANS(IPROC)/DBLE(IDEN(IPROC))
      ENDDO
      END
       
       
      COMPLEX*16 FUNCTION mat1dh(P,k,NHEL,IC,z)    
C  
C Generated by MadGraph II                                              
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL)
C  
C FOR PROCESS : u u~ -> e- e+  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NGRAPHS,    NEIGEN 
      PARAMETER (NGRAPHS=   1,NEIGEN=  1) 
      include "nexternal2.inc"
      include "emitspecinfo.inc"
      INTEGER    NWAVEFUNCS     , NCOLOR
      PARAMETER (NWAVEFUNCS=   5, NCOLOR=   1) 
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C  
C ARGUMENTS 
C  
      REAL*8 P(0:3,NEXTERNAL2)
      INTEGER NHEL(NEXTERNAL2), IC(NEXTERNAL2)
C kouhei mod
      integer z,v,k
C kouhei mod
C  
C LOCAL VARIABLES 
C  
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOL(NCOLOR,tdn), CL(NCOLOR,NCOLOR,tdn)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
C kouhei mod 
      COMPLEX*16 JINV(NCOLOR)
C kouhei mod 
      COMPLEX*16 W(18,NWAVEFUNCS)
C  
C GLOBAL VARIABLES
C  
      include "coupl.inc"
C  
C COLOR DATA
C  
      include "allcolormat1.inc"
C ----------
C BEGIN CODE
C ----------
C kouhei mod
      v=(3-z)/2
      do i=1,v
      if (i .eq. 2) nhel(emi(k))=-nhel(emi(k))
C kouhei mod
      CALL IXXXXX(P(0,1   ),ZERO ,NHEL(1   ),+1*IC(1   ),W(1,1   ))        
      CALL OXXXXX(P(0,2   ),ZERO ,NHEL(2   ),-1*IC(2   ),W(1,2   ))        
      CALL OXXXXX(P(0,3   ),ZERO ,NHEL(3   ),+1*IC(3   ),W(1,3   ))        
      CALL IXXXXX(P(0,4   ),ZERO ,NHEL(4   ),-1*IC(4   ),W(1,4   ))        
      CALL JIOXXX(W(1,1   ),W(1,2   ),GAU ,ZERO    ,AWIDTH  ,W(1,5   ))    
      CALL IOVXXX(W(1,4   ),W(1,3   ),W(1,5   ),GAL ,AMP(1   ))            
C kouhei mod
       if (i .eq. 1) then
C kouhei mod
      JAMP(   1) = -AMP(   1)
C kouhei mod
       elseif (i .eq. 2) then
C kouhei mod
      JINV(   1) = -AMP(   1)
      nhel(emi(k))=-nhel(emi(k))
C kouhei mod
       endif
C kouhei mod
C kouhei mod
      enddo
C kouhei mod
      mat1dh = 0.D0 
      DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NCOLOR
              ZTEMP = ZTEMP + CL(J,I,k)*JAMP(J)
          ENDDO
C kouhei mod
      if (z .eq. 1) then
C kouhei mod
          mat1dh =mat1dh+ZTEMP*DCONJG(JAMP(I))/DENOL(I,k) 
C kouhei mod
      elseif (z .eq. -1) then
C kouhei mod
          mat1dh =mat1dh+ZTEMP*DCONJG(JINV(I))/DENOL(I,k) 
C kouhei mod
      endif
C kouhei mod
      ENDDO
C      CALL GAUGECHECK(JAMP,ZTEMP,EIGEN_VEC,EIGEN_VAL,NCOLOR,NEIGEN) 
      END
       
       
