c Generated by AutoDipole
c Kouhei Hasegawa, Sven Moch, and Peter Uwer, 2009
c Filename:checkPK.f
c Program: checkPK evaluates P and K terms on 10 randomly chosen phase space points
c
c input  :10 randomly chosen phase space points in inputmLO.h
c output :the values of P and K terms
c 
      program checkPK
      implicit none

      double precision p(0:3,1:4),SumP,SumK,x,s
      integer i
      double precision msqLO,AL,pi,ALmsqLO,ratio,acc,mt,mb
      character*50 name
c      common /INPUTMPK/ p
c      common /usedalpha/ AL
c     common /MASS/ mt,mb
c      common /energy/s
c     common /pdfname/name
      include 'coupl.inc'
      include 'nexternal.inc'

      name='CT10nlo'
      call initpdfsetbyname(name)
      call setpara('param_card.dat',.true.)
      pi=3.141592653589793238d0
      AL=g**2*(4.d0*pi)**(-1)
      mt=tmass
      mb=bmass
      x=0.25d0
      call intPK
      stop

      call printframePK
      write(*,*) '[Leg1]'
      do i=1,10
       call readmomenta2
       call PKterm1(p,x,SumP,SumK)
       call printresultPK(i,SumP,SumK)
      enddo
      write(*,*) ''
      write(*,*) '[Leg2]'
      do i=1,10
       call readmomenta2
       call PKterm2(p,x,SumP,SumK)
       call printresultPK(i,SumP,SumK)
      enddo
      end
       
       
      subroutine readmomenta2
      implicit none
      integer idy1
      double precision dummy
      double precision p(0:3,1:4)
      common /INPUTMPK/ p
       
      open (unit=11, file ='inputmLO.h', status = 'old')
      read  (11,*) idy1, p(0,1), p(1,1), p(2,1), p(3,1)
      read  (11,*) idy1, p(0,2), p(1,2), p(2,2), p(3,2)
      read  (11,*) idy1, p(0,3), p(1,3), p(2,3), p(3,3)
      read  (11,*) idy1, p(0,4), p(1,4), p(2,4), p(3,4)
      read  (11,*) dummy  

      return
      end
       
      double precision function dot(p1,p2) 
      implicit none
      double precision p1(0:3),p2(0:3)
      dot=p1(0)*p2(0)-p1(1)*p2(1)-p1(2)*p2(2)-p1(3)*p2(3)
      end
       

      subroutine printframePK
      implicit none
      
      write(*,*) '          SumP                       SumK'
      
      return
      end
      
      subroutine printresultPK(i,SumP,SumK)
      implicit none
      
      integer i
      double precision SumP,SumK
      
      write(*,'(1x,i3,1x,2e27.15)') i,SumP,SumK
      
      return
      end

